# Netlify Configuration
# This file helps Netlify deploy your site correctly

# Build settings
[build]
  # No build command needed for static site
  publish = "."

# Redirect rules for better navigation
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Error page handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
